services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "${KAFKA_PORT:?}:${KAFKA_PORT:?}"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA_INTERNAL_HOST:?}:${KAFKA_PORT:?},CONTROLLER://${KAFKA_INTERNAL_HOST:?}:${KAFKA_CONTROLLER_PORT:?}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST:?}:${KAFKA_PORT:?}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:${KAFKA_CONTROLLER_PORT:?}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    healthcheck:
      test: ["CMD", "opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "${KAFKA_HOST:?}:${KAFKA_PORT:?}", "--list"]
      interval: 5s
      timeout: 3s
      retries: 10
  backend:
    build:
      context: ../golang/
      dockerfile: backend/Dockerfile
      target: start
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      MAIN_PORT: ${MAIN_PORT:?}
      MAIN_HOST: ${MAIN_HOST:?}

      AUTH_PORT: ${AUTH_PORT:?}
      AUTH_HOST: ${AUTH_HOST:?}
    ports:
      - "${MAIN_PORT:?}:${MAIN_PORT:?}"
