services:
  psql:
    image: postgres:18
    command: postgres
    environment:
      POSTGRES_USER: ${DB_SUPERUSER:?}
      POSTGRES_PASSWORD: ${DB_SUPERUSER_PASSWORD:?}
      POSTGRES_DB: ${DB_NAME:?}
      DB_USER: ${DB_USER:?}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_SUPERUSER:?}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA_INTERNAL_HOST:?}:${KAFKA_PORT:?},CONTROLLER://${KAFKA_INTERNAL_HOST:?}:${KAFKA_CONTROLLER_PORT:?}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST:?}:${KAFKA_PORT:?}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:${KAFKA_CONTROLLER_PORT:?}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "${KAFKA_HOST:?}:${KAFKA_PORT:?}", "--list"]
      interval: 5s
      timeout: 3s
      retries: 10
  init_kafka:
    image: apache/kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["sh", "-c"]
    command: |
      "
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server ${KAFKA_HOST:?}:${KAFKA_PORT:?} --create  --if-not-exists --topic ${KAFKA_HEALTH_TOPIC:?}
      "
  auth_service:
    build:
      context: ../golang/
      dockerfile: auth_service/Dockerfile
      target: start
    depends_on:
      init_kafka:
        condition: service_completed_successfully
      psql:
        condition: service_healthy
    environment:
      KAFKA_HOST: ${KAFKA_HOST:?}
      KAFKA_PORT: ${KAFKA_PORT:?}

      KAFKA_HEALTH_TOPIC: ${KAFKA_HEALTH_TOPIC:?}

      MAIN_PORT: ${MAIN_PORT:?}
      MAIN_HOST: ${MAIN_HOST:?}

      DB_SUPERUSER: ${DB_SUPERUSER:?}
      DB_SUPERUSER_PASSWORD: ${DB_SUPERUSER_PASSWORD:?}
      DB_USER: ${DB_USER:?}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD:?}
      DB_NAME: ${DB_NAME:?}
      DB_PORT: ${DB_PORT:?}
      DB_HOST: ${DB_HOST:?}
  backend:
    build:
      context: ../golang/
      dockerfile: backend/Dockerfile
      target: start
    depends_on:
      init_kafka:
        condition: service_completed_successfully
    environment:
      MAIN_PORT: ${MAIN_PORT:?}
      MAIN_HOST: ${MAIN_HOST:?}

    ports:
      - "${MAIN_PORT:?}:${MAIN_PORT:?}"
